/**
 * @file    Tlf35585.h
 * @brief   TLF35585/TLF35585 PMIC driver
 *
 * 16-bit SPI protocol with hardware parity.  Based on Infineon
 * code example SPI_TLF_1_KIT_TC397_TFT.
 *
 * SPI frame (16 clocks per CS assertion):
 *   Bit 15   : CMD (0=read, 1=write)
 *   Bits 14:9: Address (6 bits)
 *   Bit 8    : Parity (auto-generated by QSPI hardware)
 *   Bits 7:0 : Data (8 bits)
 *
 * Config registers have separate WRITE and READ-BACK addresses.
 * Status registers may share the same address for read and write-to-clear.
 */

#ifndef TLF35585_H
#define TLF35585_H

#include "Ifx_Types.h"

/* ================================================================== */
/*  Return codes                                                      */
/* ================================================================== */
typedef enum
{
    TLF_OK          = 0,
    TLF_ERR_SPI     = 1,
    TLF_ERR_TIMEOUT = 2,
    TLF_ERR_STATE   = 3,
    TLF_ERR_FWD     = 4,
    TLF_ERR_SPI_TIMEOUT = 5,
} Tlf35585_Status_t;

/* ================================================================== */
/*  Register addresses (from Infineon TLF35585 reference)             */
/*                                                                    */
/*  W = write address, R = read-back address.                         */
/*  Status registers use the same address for read and write-to-clear.*/
/* ================================================================== */
typedef enum
{
    TLF_W_DEVCFG0       = 0x00u,
    TLF_W_DEVCFG1       = 0x01u,
    TLF_W_DEVCFG2       = 0x02u,
    TLF_W_PROTCFG       = 0x03u,
    TLF_W_SYSPCFG0      = 0x04u,
    TLF_W_SYSPCFG1      = 0x05u,
    TLF_W_WDCFG0        = 0x06u,
    TLF_W_WDCFG1        = 0x07u,
    TLF_W_FWDCFG        = 0x08u,
    TLF_W_WWDCFG0       = 0x09u,
    TLF_W_WWDCFG1       = 0x0Au,
    /* Read-back mirrors of protected config */
    TLF_R_SYSPCFG0      = 0x0Bu,
    TLF_R_SYSPCFG1      = 0x0Cu,
    TLF_R_WDCFG0        = 0x0Du,
    TLF_R_WDCFG1        = 0x0Eu,
    TLF_R_FWDCFG        = 0x0Fu,
    TLF_R_WWDCFG0       = 0x10u,
    TLF_R_WWDCFG1       = 0x11u,
    /* Wake timer config */
    TLF_W_WKTIMCFG0     = 0x12u,
    TLF_W_WKTIMCFG1     = 0x13u,
    TLF_W_WKTIMCFG2     = 0x14u,
    /* Device control / watchdog service */
    TLF_W_DEVCTRL       = 0x15u,
    TLF_W_DEVCTRLN      = 0x16u,
    TLF_RW_WWDSCMD      = 0x17u,    /* write TRIG; read returns TRIG_STATUS  */
    TLF_W_FWDRSP        = 0x18u,
    TLF_W_FWDRSPSYNC    = 0x19u,
    /* Latched failure / status flags (see DS for clear semantics) */
    TLF_RW_SYSFAIL      = 0x1Au,    /* <-- your "missing" failure register   */
    TLF_RW_INITERR      = 0x1Bu,    /* <-- the REAL init-error register      */
    TLF_RW_IF           = 0x1Cu,
    TLF_RW_SYSSF        = 0x1Du,
    TLF_RW_WKSF         = 0x1Eu,
    TLF_RW_SPISF        = 0x1Fu,
    TLF_R_MONSF0        = 0x20u,
    TLF_R_MONSF1        = 0x21u,
    TLF_R_MONSF2        = 0x22u,
    TLF_R_MONSF3        = 0x23u,
    TLF_R_OTFAIL        = 0x24u,
    TLF_R_OTWRNSF       = 0x25u,
    TLF_R_VMONSTAT      = 0x26u,    /* <-- what you were logging as "IE"     */
    TLF_R_DEVSTAT       = 0x27u,
    TLF_R_PROTSTAT      = 0x28u,
    TLF_R_WWDSTAT       = 0x29u,
    TLF_R_FWDSTAT0      = 0x2Au,
    TLF_R_FWDSTAT1      = 0x2Bu,
    /* ABIST (control, not read-only) */
    TLF_W_ABIST_CTRL0   = 0x2Cu,
    TLF_W_ABIST_CTRL1   = 0x2Du,
    TLF_W_ABIST_SELECT0 = 0x2Eu,
    TLF_W_ABIST_SELECT1 = 0x2Fu,
    TLF_W_ABIST_SELECT2 = 0x30u,    /* Window watchdog status */
} Tlf_RegAddr_t;

/* ================================================================== */
/*  Unlock / lock keys                                                */
/* ================================================================== */
#define TLF_UNLOCK_KEY0     0xABu
#define TLF_UNLOCK_KEY1     0xEFu
#define TLF_UNLOCK_KEY2     0x56u
#define TLF_UNLOCK_KEY3     0x12u
#define TLF_LOCK_KEY0       0xDFu
#define TLF_LOCK_KEY1       0x34u
#define TLF_LOCK_KEY2       0xBEu
#define TLF_LOCK_KEY3       0xCAu

/* ================================================================== */
/*  DEVCTRL.STATEREQ values  (verified — unchanged)                   */
/* ================================================================== */
#define TLF_STATE_NONE      0x00u
#define TLF_STATE_INIT      0x01u
#define TLF_STATE_NORMAL    0x02u
#define TLF_STATE_SLEEP     0x03u
#define TLF_STATE_STANDBY   0x04u
#define TLF_STATE_WAKE      0x05u

/* ================================================================== */
/*  WDCFG0 bits  (verified — WWDETHR field added)                     */
/* ================================================================== */
#define TLF_WDCFG0_WDCYC        (1u << 0)
#define TLF_WDCFG0_WWDTSEL      (1u << 1)
#define TLF_WDCFG0_FWDEN        (1u << 2)
#define TLF_WDCFG0_WWDEN        (1u << 3)
#define TLF_WDCFG0_WWDETHR_MASK 0xF0u       /* WWD error threshold    */
#define TLF_WDCFG0_WWDETHR_SHIFT 4u

/* ================================================================== */
/*  SYSPCFG1 bits  (*** ERREN CORRECTED: was bit 0, is bit 3 ***)     */
/* ================================================================== */
#define TLF_SYSPCFG1_ERRREC_MASK 0x03u      /* recovery time, bits 1:0 */
#define TLF_SYSPCFG1_ERRRECEN    (1u << 2)  /* recovery enable         */
#define TLF_SYSPCFG1_ERREN       (1u << 3)  /* ERR pin monitor enable  */
#define TLF_SYSPCFG1_ERRSLPEN    (1u << 4)  /* monitor active in SLEEP */
#define TLF_SYSPCFG1_SS2DEL_MASK 0x60u      /* SS2 delay, bits 6:5     */

/* ================================================================== */
/*  SYSSF / SPISF bits  (verified — unchanged)                        */
/* ================================================================== */
#define TLF_SYSSF_CFGE          (1u << 0)
#define TLF_SYSSF_WWDE          (1u << 1)
#define TLF_SYSSF_FWDE          (1u << 2)
#define TLF_SYSSF_ERRMISS       (1u << 3)
#define TLF_SYSSF_TRFAIL        (1u << 4)
#define TLF_SYSSF_NOOP          (1u << 5)

#define TLF_SPISF_PARE          (1u << 0)
#define TLF_SPISF_LENE          (1u << 1)
#define TLF_SPISF_ADDRE         (1u << 2)
#define TLF_SPISF_DURE          (1u << 3)
#define TLF_SPISF_LOCK          (1u << 4)

/* ================================================================== */
/*  DEVSTAT / DEVCTRL bits  (tracker bits added; bit 4 differs!)      */
/* ================================================================== */
#define TLF_DEVSTAT_STATE_MASK  0x07u
#define TLF_DEVSTAT_VREFEN      (1u << 3)
#define TLF_DEVSTAT_STBYEN      (1u << 4)   /* status-only: StBy LDO   */
#define TLF_DEVSTAT_COMEN       (1u << 5)
#define TLF_DEVSTAT_TRK1EN      (1u << 6)
#define TLF_DEVSTAT_TRK2EN      (1u << 7)

#define TLF_DEVCTRL_STATEREQ_MASK 0x07u
#define TLF_DEVCTRL_VREFEN      (1u << 3)
                                            /* bit 4 reserved in DEVCTRL */
#define TLF_DEVCTRL_COMEN       (1u << 5)
#define TLF_DEVCTRL_TRK1EN      (1u << 6)
#define TLF_DEVCTRL_TRK2EN      (1u << 7)

/* ================================================================== */
/*  WWDSCMD bits                                                      */
/* ================================================================== */
#define TLF_WWDSCMD_TRIG        (1u << 0)   /* write: SPI trigger      */
#define TLF_WWDSCMD_TRIG_STATUS (1u << 7)   /* read: last trig received*/

#define TLF_CLEAR_STATUS        0xFFu       /* W1C full-byte clear     */

/* ================================================================== */
/*  Build-time configuration                                          */
/* ================================================================== */
#ifndef TLF_FWD_ENABLE
#define TLF_FWD_ENABLE              0u
#endif

#ifndef TLF_FAULT_POLL_INTERVAL_MS
#define TLF_FAULT_POLL_INTERVAL_MS  1000u
#endif

/* ================================================================== */
/*  Fault callback                                                    */
/* ================================================================== */
typedef void (*Tlf35585_FaultCb_t)(void);

/* ================================================================== */
/*  Event log structure (PMC-PMIC-011)                                */
/* ================================================================== */
typedef struct
{
    uint32 timestampMs;
    uint8  devstat;
    uint8  syssf;
    uint8  monsf0;
    uint8  monsf1;
    uint8  monsf2;
    uint8  initerr;
    uint8  wwdstat;
    uint8  spisf;
    uint8  errPin;
    uint8  ssPin;
    uint8  eventType;
    uint8  reserved;
} Tlf35585_Event_t;

#define TLF_EVT_INIT            0u
#define TLF_EVT_WDT_SERVICE     1u
#define TLF_EVT_FAULT           2u
#define TLF_EVT_STATE_CHANGE    3u
#define TLF_EVT_SAFE_STATE      4u
#define TLF_EVT_WDT_MISS        5u
#define TLF_WDCFG0_WDCYC        (1u << 0)
#define TLF_WDCFG0_WWDTSEL      (1u << 1)
#define TLF_WDCFG0_FWDEN        (1u << 2)
#define TLF_WDCFG0_WWDEN        (1u << 3)
#define TLF_WDCFG0_WWDETHR(n)   (((uint8)(n) & 0x0Fu) << 4)   /* WWD error threshold, bits 7:4 */

/* Init value: watchdogs off, SPI trigger preselected (used by EarlyInit) */
#define TLF_WDCFG0_INIT_DISABLED   (TLF_WDCFG0_WWDTSEL)

/* Runtime value: WWD on, SPI trigger, WDCYC=0.1ms, error threshold 9.
 * = 0x9A, matching the Infineon reference init value.                  */
#define TLF_WDCFG0_RUNTIME  (TLF_WDCFG0_WWDETHR(9u) | TLF_WDCFG0_WWDEN \
                           | TLF_WDCFG0_WWDTSEL | TLF_WDCFG0_WDCYC)  

#define TLF_WWDSTAT_WWDECNT_MASK   (0x1Fu) 

/* ================================================================== */
/*  Public API                                                        */
/* ================================================================== */

Tlf35585_Status_t Tlf35585_Init(void);

Tlf35585_Status_t Tlf35585_ReadReg(Tlf_RegAddr_t addr, uint8 *data);
Tlf35585_Status_t Tlf35585_WriteReg(Tlf_RegAddr_t addr, uint8 data);

uint8 Tlf35585_GetDevState(void);

void Tlf35585_ServiceWdt(void);
Tlf35585_Status_t Tlf35585_ServiceFwd(void);

void Tlf35585_RegisterFaultCb(Tlf35585_FaultCb_t cb);
void Tlf35585_CheckFaults(void);
boolean Tlf35585_CheckVoltageStatus(uint8 *pMonsf1, uint8 *pMonsf2);

Tlf35585_Status_t Tlf35585_GoToNormal(void);
Tlf35585_Status_t Tlf35585_GoToStandby(void);
Tlf35585_Status_t Tlf35585_GoToSleep(void);

boolean Tlf35585_IsErrActive(void);
boolean Tlf35585_IsSafeStateActive(void);

void Tlf35585_LogEvent(uint8 eventType);
void Tlf35585_DumpStatus(const char *context);

void Tlf35585_EarlyInit(void);

/* Tlf35585.h */
void Tlf35585_EnableIsrMode(void);

void Tlf35585_PublishRegSnapshot(void);

#endif /* TLF35585_H */